FROM node:lts

RUN mkdir /app
WORKDIR /app
RUN yarn global add serve
COPY package.json yarn.lock ./
RUN yarn --pure-lockfile

COPY . ./

EXPOSE 5000
CMD yarn parse && yarn glossary && yarn build && cd build && serve
