const sidebars = {
  essifLabSideBar: [
    { label: 'eSSIF-Lab',
      type: 'category',
      link: {type: 'doc', id: 'essifLab'},
      collapsed: false,
      items: [
        'essifLab-vision',
        'essifLab-objectives',
        'essifLab-principles',
        'essifLab-collaborative-understanding',
        'ssi-standards',
        'essifLab-project',
        { label: 'Mental Models',
          type: 'category',
          link: {type: 'doc', id: 'essifLab-pattern-list'},
          collapsed: true,
          items: [
            { label: 'Stable models',
              type: 'category',
              collapsed: false,
              items:
              [ 'terms/pattern-party-actor-action',
                'terms/pattern-jurisdiction',
                'terms/pattern-guardianship',
              ]
            },
            { label: 'Reviewable models',
              type: 'category',
              collapsed: true,
              items:
              [ 'terms/pattern-terminology',
                'terms/pattern-identity',
                'terms/pattern-identification',
                'terms/pattern-identifier',
                'terms/pattern-party-representation',
                'terms/pattern-governance-and-management',
                'terms/pattern-decentralized-grc',
            ]
            },
            { label: 'Envisaged models',
              type: 'category',
              collapsed: true,
              items:
              [ 'terms/pattern-world-model',
                'terms/pattern-semantics',
                'terms/pattern-trust',
                'terms/pattern-decision-making',
                'terms/pattern-mandates-delegation-hiring',
                'terms/pattern-duties-and-rights',
              ]
            },
          ],
        },
        'essifLab-glossary',
      ],
    },
    { label: 'Miscellaneous',
      type: 'category',
      link: {type: 'doc', id: 'miscellaneous'},
      collapsed: true,
      items: [
        'essifLab-fw-governance',
        'essifLab-fw-bus-arch',
        'essifLab-fw-func-arch',
        'essifLab-fw-backlog',
      ],
    },
  ],
  tev2SideBar: [
    { type: 'category',
      label: 'TEv2 Overview',
      link: {type: 'doc', id: 'tev2/tev2-overview'},
      items: [
        { type: 'autogenerated', dirName: 'tev2/overview' },
        { type: 'doc', id: 'tev2/terms/patterns/self-sovereign-terminology'},
      ]
    },
    { type: 'category',
      label: 'Roles',
      link: {type: 'doc', id: 'tev2/tev2-roles'},
      items:
      [ { type: 'category',
          label: 'Contributors',
          link: {type: 'doc', id: 'tev2/manuals/contributor'},
          items:
          [ 'tev2/manuals/contributors-wiki',
          , 'tev2/manuals/contributors-repo',
          , 'tev2/manuals/contributors-LaTeX',
          ],
        },
        { type: 'category',
          label: 'Curators',
          link: {type: 'doc', id: 'tev2/manuals/curator'},
          items:
          [ 'tev2/manuals/tev2-installation',
            'tev2/spec-tools/terminology-construction',
          ],
        },
        { type: 'doc', id: 'tev2/manuals/author'},
      ],
    },
    { type: 'category',
      label: 'Files (Structure, Specs)',
      link: {type: 'doc', id: 'tev2/tev2-spec-files'},
      items:
      [ { type: 'autogenerated', dirName: 'tev2/spec-files' } ]
    },
    { type: 'category',
      label: 'Syntax (Specs)',
      link: {type: 'doc', id: 'tev2/tev2-syntax'},
      items:
      [ { type: 'autogenerated', dirName: 'tev2/spec-syntax' },
        'tev2/spec-tools/terminology-construction',
      ]
    },
    { type: 'category',
      label: 'The Toolbox (specs)',
      link: {type: 'doc', id: 'tev2/tev2-toolbox'},
      items: [ { type: 'autogenerated', dirName: 'tev2/spec-tools' } ]
    },
    { type: 'category',
      label: 'TEv2 Glossary',
      link: {type: 'doc', id: 'tev2/tev2-glossary'},
      items: [ { type: 'autogenerated', dirName: 'tev2/terms' } ]
    },
    { type: 'category',
      label: 'Miscellanous',
      items: [ { type: 'autogenerated', dirName: 'tev2/miscellaneous' } ]
    },
  ],
};

module.exports = sidebars;
