const sidebars = {
  essifLabSideBar: [
    { type: 'category',
      label: 'eSSIF-Lab',
      link: {type: 'doc', id: 'essifLab'},
      collapsed: false,
      items: [
        'essifLab-vision',
        'essifLab-objectives',
        'essifLab-principles',
        'essifLab-project',
      ],
    },
    { type: 'category',
      label: 'Framework',
      link: {type: 'doc', id: 'essifLab-fw'},
      collapsed: true,
      items: [
        'essifLab-terminology',
        'essifLab-governance',
        'essifLab-fw-bus-arch',
        'essifLab-fw-func-arch',
      ],
    },
    { type: 'category',
      label: 'Mental Models',
      link: {type: 'doc', id: 'essifLab-pattern-list'},
      collapsed: true,
      items: [
        { type: 'category',
          label: 'Stable models',
          collapsed: true,
          items:
          [ 'terms/pattern-party-actor-action',
            'terms/pattern-jurisdiction',
            'terms/pattern-guardianship',
          ]
        },
        { type: 'category',
          label: 'Reviewable models',
          collapsed: true,
          items:
          [ 'terms/pattern-terminology',
            'terms/pattern-identity',
            'terms/pattern-governance-and-management',
        ]
        },
        { type: 'category',
          label: 'Envisaged models',
          collapsed: true,
          items:
          [ 'terms/pattern-world-model',
            'terms/pattern-identification',
            'terms/pattern-identifier',
            'terms/pattern-trust',
            'terms/pattern-decision-making',
            'terms/pattern-decentralized-grc',
            'terms/pattern-party-representation',
            'terms/pattern-mandates-delegation-hiring',
            'terms/pattern-duties-and-rights',
          ]
        },
        'essifLab-glossary',
      ],
    },
    'essifLab-fw-backlog',
  ],
  tev2SideBar: [
    'tev2-specs/tev2-overview' ,
    'tev2-specs/tev2-installation',
    'tev2-specs/tev2-administration',
    'tev2-specs/tev2-struct-directory',
    { type: 'category',
      label: 'Curated Text Structure',
      items:
      [ 'tev2-specs/tev2-struct-ctext',
        'tev2-specs/tev2-struct-ctext-header',
        'tev2-specs/tev2-struct-ctext-body',
      ],
    },
    'tev2-specs/tev2-artifact-generation',
    'tev2-specs/tev2-backlog',
  ],
};

module.exports = sidebars;